// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVBOmFRnPT5mSQPLnie0fRR8KoTWP9k6M',
    appId: '1:773530219840:web:2794d44e40b99c237676a5',
    messagingSenderId: '773530219840',
    projectId: 'fir-dev-flutter-project',
    authDomain: 'fir-dev-flutter-project.firebaseapp.com',
    storageBucket: 'fir-dev-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCxyNTOIUmW4e5bBOlUL8iVBTyvT0pP70',
    appId: '1:773530219840:android:f0b51b6df931eae77676a5',
    messagingSenderId: '773530219840',
    projectId: 'fir-dev-flutter-project',
    storageBucket: 'fir-dev-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxrHdOx-wOSdfs7PprxaNpThvaGbvY5Q8',
    appId: '1:773530219840:ios:93189f31431059d17676a5',
    messagingSenderId: '773530219840',
    projectId: 'fir-dev-flutter-project',
    storageBucket: 'fir-dev-flutter-project.appspot.com',
    iosClientId: '773530219840-mrbfjb3aaki8kvbv45g7m8bc9vf8n0mq.apps.googleusercontent.com',
    iosBundleId: 'com.sinut.simpleFlutterFirebaseCrud',
  );
}
